package thx.color;

/**
 * ...
 * @author Franco Ponticelli
 */

class NamedColors
{
	public static var aliceblue(default, null) : Rgb;
	public static var antiquewhite(default, null) : Rgb;
	public static var aqua(default, null) : Rgb;
	public static var aquamarine(default, null) : Rgb;
	public static var azure(default, null) : Rgb;
	public static var beige(default, null) : Rgb;
	public static var bisque(default, null) : Rgb;
	public static var black(default, null) : Rgb;
	public static var blanchedalmond(default, null) : Rgb;
	public static var blue(default, null) : Rgb;
	public static var blueviolet(default, null) : Rgb;
	public static var brown(default, null) : Rgb;
	public static var burlywood(default, null) : Rgb;
	public static var cadetblue(default, null) : Rgb;
	public static var chartreuse(default, null) : Rgb;
	public static var chocolate(default, null) : Rgb;
	public static var coral(default, null) : Rgb;
	public static var cornflowerblue(default, null) : Rgb;
	public static var cornsilk(default, null) : Rgb;
	public static var crimson(default, null) : Rgb;
	public static var cyan(default, null) : Rgb;
	public static var darkblue(default, null) : Rgb;
	public static var darkcyan(default, null) : Rgb;
	public static var darkgoldenrod(default, null) : Rgb;
	public static var darkgray(default, null) : Rgb;
	public static var darkgreen(default, null) : Rgb;
	public static var darkgrey(default, null) : Rgb;
	public static var darkkhaki(default, null) : Rgb;
	public static var darkmagenta(default, null) : Rgb;
	public static var darkolivegreen(default, null) : Rgb;
	public static var darkorange(default, null) : Rgb;
	public static var darkorchid(default, null) : Rgb;
	public static var darkred(default, null) : Rgb;
	public static var darksalmon(default, null) : Rgb;
	public static var darkseagreen(default, null) : Rgb;
	public static var darkslateblue(default, null) : Rgb;
	public static var darkslategray(default, null) : Rgb;
	public static var darkslategrey(default, null) : Rgb;
	public static var darkturquoise(default, null) : Rgb;
	public static var darkviolet(default, null) : Rgb;
	public static var deeppink(default, null) : Rgb;
	public static var deepskyblue(default, null) : Rgb;
	public static var dimgray(default, null) : Rgb;
	public static var dimgrey(default, null) : Rgb;
	public static var dodgerblue(default, null) : Rgb;
	public static var firebrick(default, null) : Rgb;
	public static var floralwhite(default, null) : Rgb;
	public static var forestgreen(default, null) : Rgb;
	public static var fuchsia(default, null) : Rgb;
	public static var gainsboro(default, null) : Rgb;
	public static var ghostwhite(default, null) : Rgb;
	public static var gold(default, null) : Rgb;
	public static var goldenrod(default, null) : Rgb;
	public static var gray(default, null) : Rgb;
	public static var green(default, null) : Rgb;
	public static var greenyellow(default, null) : Rgb;
	public static var grey(default, null) : Rgb;
	public static var honeydew(default, null) : Rgb;
	public static var hotpink(default, null) : Rgb;
	public static var indianred(default, null) : Rgb;
	public static var indigo(default, null) : Rgb;
	public static var ivory(default, null) : Rgb;
	public static var khaki(default, null) : Rgb;
	public static var lavender(default, null) : Rgb;
	public static var lavenderblush(default, null) : Rgb;
	public static var lawngreen(default, null) : Rgb;
	public static var lemonchiffon(default, null) : Rgb;
	public static var lightblue(default, null) : Rgb;
	public static var lightcoral(default, null) : Rgb;
	public static var lightcyan(default, null) : Rgb;
	public static var lightgoldenrodyellow(default, null) : Rgb;
	public static var lightgray(default, null) : Rgb;
	public static var lightgreen(default, null) : Rgb;
	public static var lightgrey(default, null) : Rgb;
	public static var lightpink(default, null) : Rgb;
	public static var lightsalmon(default, null) : Rgb;
	public static var lightseagreen(default, null) : Rgb;
	public static var lightskyblue(default, null) : Rgb;
	public static var lightslategray(default, null) : Rgb;
	public static var lightslategrey(default, null) : Rgb;
	public static var lightsteelblue(default, null) : Rgb;
	public static var lightyellow(default, null) : Rgb;
	public static var lime(default, null) : Rgb;
	public static var limegreen(default, null) : Rgb;
	public static var linen(default, null) : Rgb;
	public static var magenta(default, null) : Rgb;
	public static var maroon(default, null) : Rgb;
	public static var mediumaquamarine(default, null) : Rgb;
	public static var mediumblue(default, null) : Rgb;
	public static var mediumorchid(default, null) : Rgb;
	public static var mediumpurple(default, null) : Rgb;
	public static var mediumseagreen(default, null) : Rgb;
	public static var mediumslateblue(default, null) : Rgb;
	public static var mediumspringgreen(default, null) : Rgb;
	public static var mediumturquoise(default, null) : Rgb;
	public static var mediumvioletred(default, null) : Rgb;
	public static var midnightblue(default, null) : Rgb;
	public static var mintcream(default, null) : Rgb;
	public static var mistyrose(default, null) : Rgb;
	public static var moccasin(default, null) : Rgb;
	public static var navajowhite(default, null) : Rgb;
	public static var navy(default, null) : Rgb;
	public static var oldlace(default, null) : Rgb;
	public static var olive(default, null) : Rgb;
	public static var olivedrab(default, null) : Rgb;
	public static var orange(default, null) : Rgb;
	public static var orangered(default, null) : Rgb;
	public static var orchid(default, null) : Rgb;
	public static var palegoldenrod(default, null) : Rgb;
	public static var palegreen(default, null) : Rgb;
	public static var paleturquoise(default, null) : Rgb;
	public static var palevioletred(default, null) : Rgb;
	public static var papayawhip(default, null) : Rgb;
	public static var peachpuff(default, null) : Rgb;
	public static var peru(default, null) : Rgb;
	public static var pink(default, null) : Rgb;
	public static var plum(default, null) : Rgb;
	public static var powderblue(default, null) : Rgb;
	public static var purple(default, null) : Rgb;
	public static var red(default, null) : Rgb;
	public static var rosybrown(default, null) : Rgb;
	public static var royalblue(default, null) : Rgb;
	public static var saddlebrown(default, null) : Rgb;
	public static var salmon(default, null) : Rgb;
	public static var sandybrown(default, null) : Rgb;
	public static var seagreen(default, null) : Rgb;
	public static var seashell(default, null) : Rgb;
	public static var sienna(default, null) : Rgb;
	public static var silver(default, null) : Rgb;
	public static var skyblue(default, null) : Rgb;
	public static var slateblue(default, null) : Rgb;
	public static var slategray(default, null) : Rgb;
	public static var slategrey(default, null) : Rgb;
	public static var snow(default, null) : Rgb;
	public static var springgreen(default, null) : Rgb;
	public static var steelblue(default, null) : Rgb;
	public static var tan(default, null) : Rgb;
	public static var teal(default, null) : Rgb;
	public static var thistle(default, null) : Rgb;
	public static var tomato(default, null) : Rgb;
	public static var turquoise(default, null) : Rgb;
	public static var violet(default, null) : Rgb;
	public static var wheat(default, null) : Rgb;
	public static var white(default, null) : Rgb;
	public static var whitesmoke(default, null) : Rgb;
	public static var yellow(default, null) : Rgb;
	public static var yellowgreen(default, null) : Rgb;
	
	
	static function __init__()
	{
		aliceblue				= Rgb.fromInt(0xf0f8ff);
		antiquewhite			= Rgb.fromInt(0xfaebd7);
		aqua					= Rgb.fromInt(0x00ffff);
		aquamarine				= Rgb.fromInt(0x7fffd4);
		azure					= Rgb.fromInt(0xf0ffff);
		beige					= Rgb.fromInt(0xf5f5dc);
		bisque					= Rgb.fromInt(0xffe4c4);
		black					= Rgb.fromInt(0x000000);
		blanchedalmond			= Rgb.fromInt(0xffebcd);
		blue					= Rgb.fromInt(0x0000ff);
		blueviolet				= Rgb.fromInt(0x8a2be2);
		brown					= Rgb.fromInt(0xa52a2a);
		burlywood				= Rgb.fromInt(0xdeb887);
		cadetblue				= Rgb.fromInt(0x5f9ea0);
		chartreuse				= Rgb.fromInt(0x7fff00);
		chocolate				= Rgb.fromInt(0xd2691e);
		coral					= Rgb.fromInt(0xff7f50);
		cornflowerblue			= Rgb.fromInt(0x6495ed);
		cornsilk				= Rgb.fromInt(0xfff8dc);
		crimson					= Rgb.fromInt(0xdc143c);
		cyan					= Rgb.fromInt(0x00ffff);
		darkblue				= Rgb.fromInt(0x00008b);
		darkcyan				= Rgb.fromInt(0x008b8b);
		darkgoldenrod			= Rgb.fromInt(0xb8860b);
		darkgray				= Rgb.fromInt(0xa9a9a9);
		darkgreen				= Rgb.fromInt(0x006400);
		darkgrey				= Rgb.fromInt(0xa9a9a9);
		darkkhaki				= Rgb.fromInt(0xbdb76b);
		darkmagenta				= Rgb.fromInt(0x8b008b);
		darkolivegreen			= Rgb.fromInt(0x556b2f);
		darkorange				= Rgb.fromInt(0xff8c00);
		darkorchid				= Rgb.fromInt(0x9932cc);
		darkred					= Rgb.fromInt(0x8b0000);
		darksalmon				= Rgb.fromInt(0xe9967a);
		darkseagreen			= Rgb.fromInt(0x8fbc8f);
		darkslateblue			= Rgb.fromInt(0x483d8b);
		darkslategray			= Rgb.fromInt(0x2f4f4f);
		darkslategrey			= Rgb.fromInt(0x2f4f4f);
		darkturquoise			= Rgb.fromInt(0x00ced1);
		darkviolet				= Rgb.fromInt(0x9400d3);
		deeppink				= Rgb.fromInt(0xff1493);
		deepskyblue				= Rgb.fromInt(0x00bfff);
		dimgray					= Rgb.fromInt(0x696969);
		dimgrey					= Rgb.fromInt(0x696969);
		dodgerblue				= Rgb.fromInt(0x1e90ff);
		firebrick				= Rgb.fromInt(0xb22222);
		floralwhite				= Rgb.fromInt(0xfffaf0);
		forestgreen				= Rgb.fromInt(0x228b22);
		fuchsia					= Rgb.fromInt(0xff00ff);
		gainsboro				= Rgb.fromInt(0xdcdcdc);
		ghostwhite				= Rgb.fromInt(0xf8f8ff);
		gold					= Rgb.fromInt(0xffd700);
		goldenrod				= Rgb.fromInt(0xdaa520);
		gray					= Rgb.fromInt(0x808080);
		green					= Rgb.fromInt(0x008000);
		greenyellow				= Rgb.fromInt(0xadff2f);
		grey					= Rgb.fromInt(0x808080);
		honeydew				= Rgb.fromInt(0xf0fff0);
		hotpink					= Rgb.fromInt(0xff69b4);
		indianred				= Rgb.fromInt(0xcd5c5c);
		indigo					= Rgb.fromInt(0x4b0082);
		ivory					= Rgb.fromInt(0xfffff0);
		khaki					= Rgb.fromInt(0xf0e68c);
		lavender				= Rgb.fromInt(0xe6e6fa);
		lavenderblush			= Rgb.fromInt(0xfff0f5);
		lawngreen				= Rgb.fromInt(0x7cfc00);
		lemonchiffon			= Rgb.fromInt(0xfffacd);
		lightblue				= Rgb.fromInt(0xadd8e6);
		lightcoral				= Rgb.fromInt(0xf08080);
		lightcyan				= Rgb.fromInt(0xe0ffff);
		lightgoldenrodyellow	= Rgb.fromInt(0xfafad2);
		lightgray				= Rgb.fromInt(0xd3d3d3);
		lightgreen				= Rgb.fromInt(0x90ee90);
		lightgrey				= Rgb.fromInt(0xd3d3d3);
		lightpink				= Rgb.fromInt(0xffb6c1);
		lightsalmon				= Rgb.fromInt(0xffa07a);
		lightseagreen			= Rgb.fromInt(0x20b2aa);
		lightskyblue			= Rgb.fromInt(0x87cefa);
		lightslategray			= Rgb.fromInt(0x778899);
		lightslategrey			= Rgb.fromInt(0x778899);
		lightsteelblue			= Rgb.fromInt(0xb0c4de);
		lightyellow				= Rgb.fromInt(0xffffe0);
		lime					= Rgb.fromInt(0x00ff00);
		limegreen				= Rgb.fromInt(0x32cd32);
		linen					= Rgb.fromInt(0xfaf0e6);
		magenta					= Rgb.fromInt(0xff00ff);
		maroon					= Rgb.fromInt(0x800000);
		mediumaquamarine		= Rgb.fromInt(0x66cdaa);
		mediumblue				= Rgb.fromInt(0x0000cd);
		mediumorchid			= Rgb.fromInt(0xba55d3);
		mediumpurple			= Rgb.fromInt(0x9370db);
		mediumseagreen			= Rgb.fromInt(0x3cb371);
		mediumslateblue			= Rgb.fromInt(0x7b68ee);
		mediumspringgreen		= Rgb.fromInt(0x00fa9a);
		mediumturquoise			= Rgb.fromInt(0x48d1cc);
		mediumvioletred			= Rgb.fromInt(0xc71585);
		midnightblue			= Rgb.fromInt(0x191970);
		mintcream				= Rgb.fromInt(0xf5fffa);
		mistyrose				= Rgb.fromInt(0xffe4e1);
		moccasin				= Rgb.fromInt(0xffe4b5);
		navajowhite				= Rgb.fromInt(0xffdead);
		navy					= Rgb.fromInt(0x000080);
		oldlace					= Rgb.fromInt(0xfdf5e6);
		olive					= Rgb.fromInt(0x808000);
		olivedrab				= Rgb.fromInt(0x6b8e23);
		orange					= Rgb.fromInt(0xffa500);
		orangered				= Rgb.fromInt(0xff4500);
		orchid					= Rgb.fromInt(0xda70d6);
		palegoldenrod			= Rgb.fromInt(0xeee8aa);
		palegreen				= Rgb.fromInt(0x98fb98);
		paleturquoise			= Rgb.fromInt(0xafeeee);
		palevioletred			= Rgb.fromInt(0xdb7093);
		papayawhip				= Rgb.fromInt(0xffefd5);
		peachpuff				= Rgb.fromInt(0xffdab9);
		peru					= Rgb.fromInt(0xcd853f);
		pink					= Rgb.fromInt(0xffc0cb);
		plum					= Rgb.fromInt(0xdda0dd);
		powderblue				= Rgb.fromInt(0xb0e0e6);
		purple					= Rgb.fromInt(0x800080);
		red						= Rgb.fromInt(0xff0000);
		rosybrown				= Rgb.fromInt(0xbc8f8f);
		royalblue				= Rgb.fromInt(0x4169e1);
		saddlebrown				= Rgb.fromInt(0x8b4513);
		salmon					= Rgb.fromInt(0xfa8072);
		sandybrown				= Rgb.fromInt(0xf4a460);
		seagreen				= Rgb.fromInt(0x2e8b57);
		seashell				= Rgb.fromInt(0xfff5ee);
		sienna					= Rgb.fromInt(0xa0522d);
		silver					= Rgb.fromInt(0xc0c0c0);
		skyblue					= Rgb.fromInt(0x87ceeb);
		slateblue				= Rgb.fromInt(0x6a5acd);
		slategray				= Rgb.fromInt(0x708090);
		slategrey				= Rgb.fromInt(0x708090);
		snow					= Rgb.fromInt(0xfffafa);
		springgreen				= Rgb.fromInt(0x00ff7f);
		steelblue				= Rgb.fromInt(0x4682b4);
		tan						= Rgb.fromInt(0xd2b48c);
		teal					= Rgb.fromInt(0x008080);
		thistle					= Rgb.fromInt(0xd8bfd8);
		tomato					= Rgb.fromInt(0xff6347);
		turquoise				= Rgb.fromInt(0x40e0d0);
		violet					= Rgb.fromInt(0xee82ee);
		wheat					= Rgb.fromInt(0xf5deb3);
		white					= Rgb.fromInt(0xffffff);
		whitesmoke				= Rgb.fromInt(0xf5f5f5);
		yellow					= Rgb.fromInt(0xffff00);
		yellowgreen				= Rgb.fromInt(0x9acd32);
	}
}